name: Build

on:
  workflow_run:
    workflows: [Translate]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    defaults:
      run:
        working-directory: ./site # Set the default working directory to "site"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        # ADD YOUR CUSTOM DEPENDENCY UPGRADE COMMANDS BELOW
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install JS dependencies and build
        working-directory: ./site # Change the working directory for this step
        # ADD YOUR CUSTOM DEPENDENCY UPGRADE COMMANDS BELOW
        run: |
          npm ci && npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: biel-nocms
          directory: site/dist # Set the directory to "frontend/dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
