name: Translate

on:
  workflow_dispatch:
  push:
    paths:
      - "site/**"

jobs:
  run-my-action:
    name: start Translation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          cd translate &&
          npm ci &&
          npm run build

      - name: Save git diff result
        id: save-git-diff
        run: |
          echo "diff=$(git diff --unified=0 HEAD^ HEAD)" >> "$GITHUB_OUTPUT"
      - uses: ./translate
        env:
          NODE_ENV: CI
        with:
          # todo: change to key
          deepLKey: ${{ secrets.DEEPLKEY }}
          prevDiff: ${{steps.save-git-diff.outputs.diff}}

      - name: setup git config
        run: |
          git config user.name "Translation Bot"
          git config user.email "<>"
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain > changes.txt
          if [ -s changes.txt ]; then
            echo "Changes detected."
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected."
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Process changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Auto updating text file"
          git fetch
          git push
