name: Translate

on:
  workflow_dispatch:
  push:
    paths:
      - "site/**"

jobs:
  run-my-action:
    name: start Translation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          cd translate &&
          npm ci &&
          npm run build

      - uses: ./translate
        env:
          NODE_ENV: CI
        with:
          # todo: change to key
          deepLKey: ${{ secrets.DEEPLKEY }}
      - name: setup git config
        run: |
          git config user.name "Translation Bot"
          git config user.email "<>"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating text file"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
